# Generated by Django 5.1.2 on 2024-10-15 13:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='additional', verbose_name='Иконка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
                'verbose_name_plural': 'Дополнительная информация',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыт',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('image', models.ImageField(null=True, upload_to='personal', verbose_name='Картинка баннера')),
                ('image_mobile', models.ImageField(null=True, upload_to='personal', verbose_name='Картинка баннера для мобилки')),
                ('resume_file', models.FileField(upload_to='personal', verbose_name='Файл резюме')),
                ('about_me', ckeditor.fields.RichTextField(verbose_name='Текст обо мне')),
                ('linked_in', models.CharField(default='', max_length=255, verbose_name='Ссылка на LinkedIn')),
                ('github', models.CharField(default='', max_length=255, verbose_name='Ссылка на GitHub')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Почта')),
                ('phone_number', models.CharField(default='', max_length=255, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Персональная информальная',
                'verbose_name_plural': 'Персональная информация',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Картинка')),
                ('image_mobile', models.ImageField(upload_to='portfolio', verbose_name='Картинка для мобилки')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('github_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на гитхаб проекта')),
                ('live_demo', models.TextField(blank=True, null=True, verbose_name='Ссылка на демо')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='work_experience', verbose_name='Иконка компании')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('position', models.CharField(max_length=255, verbose_name='Позиция на работе')),
                ('responsibility', ckeditor.fields.RichTextField(verbose_name='Обязанности на работе')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
    ]
