# Generated by Django 5.1.2 on 2024-10-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_personalinfo_options_alter_additionalinfo_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='leadership',
            field=models.BooleanField(default=False, verbose_name='Лидерство'),
        ),
    ]
