# Generated by Django 5.1.2 on 2024-10-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_workexperience_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='personal_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='mainpage.personalinfo'),
        ),
    ]
