# Generated by Django 5.1.2 on 2024-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0005_alter_personalinfo_resume_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=255, verbose_name="Почта")),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Связь",
                "verbose_name_plural": "Связи",
            },
        ),
    ]
